### ISSUE TITLE
Group Meeting 191021

### ISSUE THREAD

**Issue by adriana-madi** [IBP-21-22/intbioproj#5]
The following contains notes and thoughts transcribed from the meeting today:

**Questions:**
How many pathways?
	Binary to sort if the pathway is in there or not
How many requests can we have on KEGG?
Why is Kegg so bad?
	Should we contact them?

**Discussion**:
Set a meeting with supervisors for Thursday or Friday
	confirmed for Thursday

Maybe look at the pathway category (?) aswell
	-> maybe do this at a later stage (as a clustering, labelling process, see if we find something interesting)

Work with Kegg API: identify which genes correspond with which 220 pathways that are found in s. cerevisiae 
	Some issues with the query

Excel -> retrieve genes -> compare to pathway
	Start with one gene: try to find relevant pathways

Filtering -> should we filter by pathway? Filter by GO?
		-> understand where the difference lies, then we can cluster the results based either on GO (isoform?) pathway? To understand expression in gene based on that.

Preparation for meeting with Raúl:
-> Sequence Features -> other possible methods other than (gene length, AT/GC ratio and transcription factors)
	maybe find some more papers on this to understand this better. 		These will be features for the pattern detection algorithm.

-> coding strand and the isoelectric point, what relevance is there with terminator sequence?

-> Take a couple days to see other than pathway/functional?

-> Another idea of classification other than function/pathway could be essential vs non-essential genes to see a relationship between UTR length/ AC/GC / TF stuff. 

-> Filter the GO terms (there are so many 5000)
	-> 45000 GO terms for all 3 categories 
	-> reduce further by grouping them in Pathway/Essential/Function

Gene -> Intensity -> All possible variables -> GO Term
With binary values and do variable subset selection

Gene with all properties -> then analysis to find out which features are relevant -> then we do classification/clustering 

Determine by what we are investigating: 
Multicollinearity -> cannot model as a linear model
instead: PCA or create a new space of features that are independent, or apply for example PLS method to map to difference space using specific transformation

**Task List:**
For Thursday:
- [x] How to reduce dimensionality (stuff is hierarchy)
    - [x] Adriana & Dada
- [x] Look at data & filter what we think is important or not
    - [x] Vassilis 
- [ ] Different kinds of fluorescence and which should we use
    - [ ] Lore 

1. How do we want to reduce dimensionality? (Avoid collinearity)
        1. Questions to consider: what kind of data are we working with? Possible noise?
2. Looking into coding strand/isoelectric point as possible features?
        1. Read some literatures. etc…
3. Grouping of GO Terms into pathways or categories?
4. Variable importance?
    1. Random forest -> what is important feature?
5. Import Essential Database into DB
    1. For Essential vs Non-essential genes

**Things to do better next time:**
Have a clear agenda to save time
Stand-up 5 minutes at beginning of meeting to express progress/problems/etc.. (maybe we can do this on another day before the big meeting? I.e: 5 minutes after the IBP lecture?)
